version: '3.8'

services:

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=apas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "d-base:/var/lib/postgresql/data"

  apas:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/apas
    image: apas
    container_name: apas
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - apas:/data

volumes:
  d-base:
  apas: